### ISSUE TITLE
Add steam, gnome-boxes, gnome-games, darktable ?

### ISSUE THREAD

**Issue by DraGiuS** [Rizwan-Hasan/MagpieOS#1]
Some suggestions.

**Comment by DraGiuS** [comment]
.

**Comment by Rizwan-Hasan** [comment]
Actually to save space I removed uneeded packages. There are many users who aren't gonna use steam, gnome-boxes and darktable. But also people like you there who needs those. And I think those who needs further packaged they can install it using pacman (command line) or pamac. I haven't any problem to add those packages. But I am trying to save space to reduce iso size. Thanks
